### ISSUE TITLE
borwser.js在windows下的safari中报错

### ISSUE THREAD

**Issue by mzpuu** [gucong3000/browser.js#1]
浏览器是Windows下的safari ，版本5.1.7，好像别的版本也有问题。
报错信息：'undefined' is not an object (evaluating 'win[obj].prototype')
报错位置：第231行     obj = win[obj].prototype;

Object.getOwnPropertyNames()支持safari  5以上；
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames

跑来问下作者是什么问题？不过windows下的safari份额不是很多，作者有空请看一下，：）

**Comment by gucong3000** [comment]
@mzpuu 感谢你的汇报，此问题已经修复。但是请注意，safari windows版本在2012年之后停止维护，只更新OS X、iOS版本，目前最新版本为9.1。
