### ISSUE TITLE
在open版本为43.*的浏览器上不能正常获取版本号

### ISSUE THREAD

**Issue by wayung** [gucong3000/browser.js#2]
显示为“undefined",其他的浏览器都能正常获取版本号

**Comment by gucong3000** [comment]
open是啥浏览器？求下载地址

**Comment by gucong3000** [comment]
![image](https://cloud.githubusercontent.com/assets/1171691/25085531/58cf7ab6-2395-11e7-81e8-ca22a640f7a9.png)

已在Opera 44.0.2510.1159 (PGO)下测试正常，测试的实例为[test.html](test.html)

**Comment by wayung** [comment]
不好意思，口误。之前用的是Opera测试版本号，所以返回undefined，用OPR才能正确地返回版本号，谢谢了!
